# Generated by Django 5.1.1 on 2024-10-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
