# Generated by Django 5.1.1 on 2024-10-18 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
    ]
