# Generated by Django 4.2 on 2025-01-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_alter_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='replied',
            field=models.BooleanField(default=False),
        ),
    ]
