# Generated by Django 5.1.1 on 2024-10-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_rename_profile_image_about_about_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
