# Generated by Django 5.1.1 on 2024-10-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_has_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_colors',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
