# Generated by Django 4.2 on 2025-01-04 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_colors',
        ),
    ]
